import { SupabaseClient } from '@supabase/supabase-js';
import {
    WarehouseTransfer,
    TransferWithDetails,
    TransferStatus,
    TransferStats,
    ReceiveTransferLine,
} from '../types';
import { inventoryService } from '@/features/inventory/services/inventoryService';

// ─── Types ────────────────────────────────────────────────────────────────────

interface TransferFilters {
    status?: string;
    search?: string;
}

// ─── Service ──────────────────────────────────────────────────────────────────

export const transferService = {
    /**
     * Retrieves the tenant ID for the authenticated user via RPC.
     * Falls back to direct table lookup if RPC fails.
     */
    async getTenantId(client: SupabaseClient): Promise<string> {
        const { data, error } = await client.rpc('get_my_tenant_id');
        if (!error && data) return data as string;

        const { data: tenantData } = await client
            .from('tenants')
            .select('id')
            .limit(1)
            .maybeSingle();

        if (!tenantData?.id) throw new Error('No se encontró tenant para el usuario actual');
        return tenantData.id as string;
    },

    /**
     * Fetches all warehouse transfers with related warehouse and line data.
     * Supports optional filtering by status or search term.
     */
    async getTransfers(
        client: SupabaseClient,
        filters?: TransferFilters
    ): Promise<TransferWithDetails[]> {
        let query = client
            .from('warehouse_transfers')
            .select(`
                *,
                from_warehouse:warehouses!from_warehouse_id(name),
                to_warehouse:warehouses!to_warehouse_id(name),
                lines:warehouse_transfer_lines(
                    id, transfer_id, product_id, qty, qty_received, notes,
                    product:products(name, sku)
                )
            `)
            .order('created_at', { ascending: false });

        if (filters?.status && filters.status !== 'all') {
            query = query.eq('status', filters.status);
        }

        const { data, error } = await query;
        if (error) throw error;

        let results = (data ?? []) as TransferWithDetails[];

        if (filters?.search) {
            const s = filters.search.toLowerCase();
            results = results.filter(
                (t) =>
                    t.transfer_number?.toLowerCase().includes(s) ||
                    (t.from_warehouse as any)?.name?.toLowerCase().includes(s) ||
                    (t.to_warehouse as any)?.name?.toLowerCase().includes(s)
            );
        }

        return results;
    },

    /**
     * Fetches a single transfer by ID with all related data.
     */
    async getTransferById(
        client: SupabaseClient,
        id: string
    ): Promise<TransferWithDetails> {
        const { data, error } = await client
            .from('warehouse_transfers')
            .select(`
                *,
                from_warehouse:warehouses!from_warehouse_id(name),
                to_warehouse:warehouses!to_warehouse_id(name),
                lines:warehouse_transfer_lines(
                    id, transfer_id, product_id, qty, qty_received, notes,
                    product:products(name, sku)
                )
            `)
            .eq('id', id)
            .single();

        if (error) throw error;
        return data as TransferWithDetails;
    },

    /**
     * Creates a new transfer header and its lines.
     * transfer_number is auto-generated by a DB trigger.
     */
    async createTransfer(
        client: SupabaseClient,
        transfer: WarehouseTransfer
    ): Promise<{ id: string; transfer_number: string }> {
        const tenant_id = await this.getTenantId(client);
        const { lines, ...header } = transfer;

        const { data: created, error: headerError } = await client
            .from('warehouse_transfers')
            .insert({ ...header, tenant_id, status: 'DRAFT' as TransferStatus })
            .select('id, transfer_number')
            .single();

        if (headerError) throw headerError;

        const lineData = lines.map((l) => ({
            transfer_id: created.id,
            product_id: l.product_id,
            qty: l.qty,
            qty_received: 0,
            notes: l.notes ?? null,
        }));

        const { error: linesError } = await client
            .from('warehouse_transfer_lines')
            .insert(lineData);

        if (linesError) throw linesError;

        return { id: created.id, transfer_number: created.transfer_number };
    },

    /**
     * Sends a DRAFT transfer to IN_TRANSIT.
     * Creates OUT inventory movements from the source warehouse for each line.
     */
    async sendTransfer(client: SupabaseClient, id: string): Promise<void> {
        const transfer = await this.getTransferById(client, id);

        if (transfer.status !== 'DRAFT') {
            throw new Error(
                `Solo se pueden enviar traslados en estado BORRADOR. Estado actual: "${transfer.status}"`
            );
        }

        const now = new Date().toISOString();

        const { data: { user } } = await client.auth.getUser();
        if (!user) throw new Error('No autorizado');

        // Create OUT movements for each line from source warehouse
        const movementErrors: string[] = [];
        for (const line of transfer.lines) {
            try {
                const avgCost = await inventoryService.getAvgCost(
                    client,
                    line.product_id,
                    transfer.from_warehouse_id
                );

                await inventoryService.createMovement(client, {
                    product_id: line.product_id,
                    warehouse_id: transfer.from_warehouse_id,
                    type: 'OUT',
                    qty: line.qty,
                    cost: avgCost,
                    occurred_at: now,
                    ref_doc_type: 'WAREHOUSE_TRANSFER',
                    ref_doc_id: id,
                });
            } catch (err: unknown) {
                const msg = err instanceof Error ? err.message : 'Error desconocido';
                movementErrors.push(`Producto ${line.product_id.substring(0, 8)}: ${msg}`);
                console.error(`[transferService.sendTransfer] Movement error for product ${line.product_id}:`, err);
            }
        }

        // Update header status to IN_TRANSIT
        const { error: updateError } = await client
            .from('warehouse_transfers')
            .update({
                status: 'IN_TRANSIT' as TransferStatus,
                transferred_by: user.id,
                transferred_at: now,
                updated_at: now,
            })
            .eq('id', id)
            .eq('status', 'DRAFT');

        if (updateError) throw updateError;

        if (movementErrors.length > 0) {
            throw new Error(
                `Traslado enviado con advertencias. Algunos movimientos fallaron: ${movementErrors.join('; ')}`
            );
        }
    },

    /**
     * Receives an IN_TRANSIT transfer at the destination warehouse.
     * Updates qty_received per line and creates IN inventory movements at the target warehouse.
     * Sets status to RECEIVED once all lines are fully received.
     */
    async receiveTransfer(
        client: SupabaseClient,
        id: string,
        lines: ReceiveTransferLine[]
    ): Promise<void> {
        const transfer = await this.getTransferById(client, id);

        if (transfer.status !== 'IN_TRANSIT') {
            throw new Error(
                `Solo se pueden recibir traslados en estado EN_TRÁNSITO. Estado actual: "${transfer.status}"`
            );
        }

        const { data: { user } } = await client.auth.getUser();
        if (!user) throw new Error('No autorizado');

        const now = new Date().toISOString();
        const activeLines = lines.filter((l) => l.qty_received > 0);

        if (activeLines.length === 0) {
            throw new Error('Debe recibir al menos un artículo con cantidad mayor a cero');
        }

        // Update qty_received for each provided line
        for (const rl of activeLines) {
            const { error } = await client
                .from('warehouse_transfer_lines')
                .update({ qty_received: rl.qty_received })
                .eq('id', rl.line_id)
                .eq('transfer_id', id);

            if (error) {
                console.error(`[transferService.receiveTransfer] Line update error for ${rl.line_id}:`, error);
            }
        }

        // Create IN movements for each received line at destination warehouse
        const movementErrors: string[] = [];
        for (const rl of activeLines) {
            const transferLine = transfer.lines.find((l) => l.id === rl.line_id);
            if (!transferLine) continue;

            try {
                // Use original source avg cost at time of send as the cost basis
                const avgCost = await inventoryService.getAvgCost(
                    client,
                    transferLine.product_id,
                    transfer.from_warehouse_id
                );

                await inventoryService.createMovement(client, {
                    product_id: transferLine.product_id,
                    warehouse_id: transfer.to_warehouse_id,
                    type: 'IN',
                    qty: rl.qty_received,
                    cost: avgCost,
                    occurred_at: now,
                    ref_doc_type: 'WAREHOUSE_TRANSFER',
                    ref_doc_id: id,
                });
            } catch (err: unknown) {
                const msg = err instanceof Error ? err.message : 'Error desconocido';
                movementErrors.push(`Producto ${transferLine.product_id.substring(0, 8)}: ${msg}`);
                console.error(
                    `[transferService.receiveTransfer] Movement error for product ${transferLine.product_id}:`,
                    err
                );
            }
        }

        // Determine new status based on received quantities
        const { data: updatedLines } = await client
            .from('warehouse_transfer_lines')
            .select('qty, qty_received')
            .eq('transfer_id', id);

        const allReceived = updatedLines?.every(
            (l) => Number(l.qty_received) >= Number(l.qty)
        );

        const newStatus: TransferStatus = allReceived ? 'RECEIVED' : 'IN_TRANSIT';

        const updatePayload: Record<string, unknown> = {
            status: newStatus,
            updated_at: now,
        };

        if (newStatus === 'RECEIVED') {
            updatePayload.received_by = user.id;
            updatePayload.received_at = now;
        }

        const { error: updateError } = await client
            .from('warehouse_transfers')
            .update(updatePayload)
            .eq('id', id);

        if (updateError) throw updateError;

        if (movementErrors.length > 0) {
            throw new Error(
                `Recepción registrada con advertencias. Algunos movimientos fallaron: ${movementErrors.join('; ')}`
            );
        }
    },

    /**
     * Cancels a DRAFT transfer. Only DRAFT transfers can be cancelled.
     */
    async cancelTransfer(client: SupabaseClient, id: string): Promise<void> {
        const { error } = await client
            .from('warehouse_transfers')
            .update({
                status: 'CANCELLED' as TransferStatus,
                updated_at: new Date().toISOString(),
            })
            .eq('id', id)
            .eq('status', 'DRAFT');

        if (error) throw error;
    },

    /**
     * Returns a summary count of transfers grouped by status.
     */
    async getStats(client: SupabaseClient): Promise<TransferStats> {
        const { data, error } = await client
            .from('warehouse_transfers')
            .select('status');

        if (error) throw error;

        const rows = (data ?? []) as Array<{ status: string }>;

        return {
            total: rows.length,
            drafts: rows.filter((r) => r.status === 'DRAFT').length,
            inTransit: rows.filter((r) => r.status === 'IN_TRANSIT').length,
            received: rows.filter((r) => r.status === 'RECEIVED').length,
            cancelled: rows.filter((r) => r.status === 'CANCELLED').length,
        };
    },
};
